from django.core.management.base import BaseCommand
from game.models import Categoria, Frase, ConfigurazioneGioco
from django.contrib.auth.models import User

class Command(BaseCommand):
    help = 'Popola il database con categorie cinema/storia/animali e crea Superuser se manca'

    def handle(self, *args, **kwargs):
        # ---------------------------------------------------------
        # 1. CREAZIONE SUPERUSER AUTOMATICA (Cruciale per Render)
        # ---------------------------------------------------------
        nome_admin = "admin"
        pass_admin = "admin123"
        
        if not User.objects.filter(username=nome_admin).exists():
            User.objects.create_superuser(nome_admin, 'admin@example.com', pass_admin)
            self.stdout.write(self.style.SUCCESS(f'✅ UTENTE ADMIN CREATO! User: {nome_admin} / Pass: {pass_admin}'))
        else:
            self.stdout.write(self.style.WARNING('ℹ️ Utente admin già esistente.'))

        # ---------------------------------------------------------
        # 2. CONFIGURAZIONE ROUND
        # ---------------------------------------------------------
        if not ConfigurazioneGioco.objects.exists():
            ConfigurazioneGioco.objects.create(numero_round_per_partita=3)
            self.stdout.write(self.style.SUCCESS('✅ Configurazione Round creata (3 round).'))

        # ---------------------------------------------------------
        # 3. POPOLAMENTO FRASI (Il tuo nuovo Dataset)
        # ---------------------------------------------------------
        dataset = {
            "CINEMA FRASI ICONICHE PARAFRASATE": [
                ("CHE LA FORZA POSSA ACCOMPAGNARTI SEMPRE IN OGNI BATTAGLIA DELLA GALASSIA", "FILM DI FANTASCIENZA"),
                ("LA VITA SOMIGLIA A UNA SCATOLA DI CIOCCOLATINI E NON SAI MAI COSA TROVI", "FILM DRAMMATICO"),
                ("TI FARO UNA PROPOSTA CHE NON POTRAI RIFIUTARE DETTA CON CALMA E MINACCIA", "FILM DI MAFIA"),
                ("NON E IL CUCCHIAIO CHE SI PIEGA MA IL TUO MODO DI GUARDARE LA REALTA", "FILM CULT"),
                ("NON CONTA QUANTO COLPISCI MA QUANTO RESISTI E CONTINUI AD ANDARE AVANTI", "FILM SPORTIVO"),
                ("NESSUN POSTO AL MONDO E COME CASA QUANDO FINISCE UN VIAGGIO STRANO", "FILM FANTASTICO"),
                ("QUESTO POTREBBE ESSERE L INIZIO DI UNA GRANDE AMICIZIA NATA PER CASO", "FILM ROMANTICO"),
                ("PROMETTO CHE TORNERO PRESTO CON LO SGUARDO DI ACCIAIO E PASSI PESANTI", "FILM D AZIONE"),
                ("VOGLIO TELEFONARE PER DIRE CHE DESIDERO SOLO TORNARE A CASA", "FILM FANTASCIENZA"),
                ("LA VITA TROVA SEMPRE UNA STRADA ANCHE QUANDO PENSI DI AVER CONTROLLATO TUTTO", "FILM CON DINOSAURI")
            ],
            "CINEMA SCENE FAMOSE": [
                ("UN ARCHEOLOGO CON CAPPELLO E FRUSTA CORRE DAVANTI A UNA ROCCIA GIGANTE", "AVVENTURA"),
                ("DUE AMANTI A PRUA CON LE BRACCIA APERTE COME SE STESSERO VOLANDO", "FILM ROMANTICO"),
                ("UN DETECTIVE CAMMINA SOTTO LA PIOGGIA TRA LUCI AL NEON E OMBRE", "THRILLER"),
                ("UN MAGO RAGAZZO CON OCCHIALI SCOPRE UNA SCUOLA SEGRETA PIENA DI INCANTESIMI", "MAGIA"),
                ("UN EROE IN MASCHERA OSCURA OSSERVA LA CITTA DALL ALTO DI UN GRATTACIELO", "SUPEREROI"),
                ("UN RE LEONE GUARDA IL CIELO E RICORDA LE PAROLE DEL PADRE", "ANIMAZIONE"),
                ("UN ROBOT SOLITARIO RACCOGLIE OGGETTI SU UNA TERRA DESERTA PIENA DI SILENZIO", "FUTURO"),
                ("UNA CORSA IN AUTO TRA TRAFFICO E POLIZIA CON MUSICA A TUTTO VOLUME", "INSEGUIMENTO"),
                ("UN UOMO IN COMPLETO NERO SCHIVA COLPI AL RALLENTATORE COME FOSSE IMPOSSIBILE", "AZIONE"),
                ("UNA BATTAGLIA SOTTO LA PIOGGIA CON SPADATE E URA CHE NON FINISCONO", "FILM EPICO")
            ],
            "EVENTI STORICI MONDIALI": [
                ("SBARCO IN NORMANDIA IL SEI GIUGNO MILLENOVECENTOQUARANTAQUATTRO", "SECONDA GUERRA MONDIALE"),
                ("CADUTA DEL MURO DI BERLINO CHE DIVIDEVA UNA CITTA IN DUE MONDI", "GUERRA FREDDA"),
                ("PRIMO PASSO UMANO SULLA LUNA CON UNA FRASE CHE FECE IL GIRO DEL MONDO", "SPAZIO"),
                ("FIRMA DEL TRATTATO CHE POSE FINE A UNA GUERRA DEVASTANTE IN EUROPA", "PACE"),
                ("SCOPERTA DELL AMERICA CON TRE NAVI E UN VIAGGIO SENZA CERTEZZE", "ESPLORAZIONI"),
                ("RIVOLUZIONE FRANCESE CON PRESA DELLA BASTIGLIA E CAMBIAMENTO RADICALE", "RIVOLUZIONE"),
                ("AFFONDA IL TITANIC NELLA NOTTE GELIDA DOPO L IMPATTO CON UN ICEBERG", "TRAGEDIA"),
                ("PRIMO UOMO NELLO SPAZIO ORBITA INTORNO ALLA TERRA E TORNA VIVO", "COSMONAUTA"),
                ("FINE DELLA SECONDA GUERRA MONDIALE CON FESTEGGIAMENTI IN STRADA", "STORIA"),
                ("SCOPERTA DELLA PENICILLINA CHE CAMBIO PER SEMPRE LA MEDICINA MODERNA", "SCIENZA")
            ],
            "EVENTI STORICI ITALIANI": [
                ("ERUZIONE DEL VESUVIO CHE SEPPELLI POMPEI SOTTO CENERE E LAPILLI", "ANTICA ROMA"),
                ("UNIFICAZIONE D ITALIA CON NASCITA DEL REGNO E SPERANZE DI UN POPOLO", "RISORGIMENTO"),
                ("ROMA DIVENTA CAPITALE E CAMBIA IL VOLTO POLITICO DELLA NAZIONE", "STORIA D ITALIA"),
                ("ALLUVIONE DI FIRENZE CON FANGO OVUNQUE E VOLONTARI DA TUTTO IL MONDO", "NOVECENTO"),
                ("COSTRUZIONE DEL COLOSSEO COME SIMBOLO DI POTENZA E SPETTACOLO", "IMPERI ROMANI"),
                ("PROCESSI E INCHIESTE CHE SCOSSONO LA POLITICA ITALIANA NEGLI ANNI NOVANTA", "CRONACA"),
                ("IL PRIMO TRAFORO CHE ATTRAVERSA LA MONTAGNA E COLLEGA DUE STATI", "INGEGNERIA"),
                ("FESTA DELLA REPUBBLICA CON IL REFERENDUM CHE CAMBIA LA FORMA DI STATO", "REFERENDUM"),
                ("TERREMOTO DEVASTANTE CON PAESI DISTRUTTI E RICOSTRUZIONE LUNGHISSIMA", "CALAMITA"),
                ("LA NASCITA DI UN GRANDE MARCHIO AUTOMOBILISTICO CHE DIVENTA SIMBOLO ITALIANO", "MOTORI")
            ],
            "SCOPERTE E INVENZIONI": [
                ("INVENZIONE DELLA STAMPA A CARATTERI MOBILI CHE DIFFONDE LIBRI OVUNQUE", "COMUNICAZIONE"),
                ("SCOPERTA DEL DNA COME CODICE DELLA VITA CON STRUTTURA A DOPPIA ELICA", "BIOLOGIA"),
                ("PRIMA LAMPADINA ELETTRICA CHE PORTA LUCE NELLE CASE E NELLE STRADE", "ELETTRICITA"),
                ("PRIMO TELEFONO CHE PERMETTE DI PARLARE A DISTANZA SENZA MUOVERSI", "TECNOLOGIA"),
                ("PRIMA RADIO CHE TRASMETTE VOCI E MUSICA NELL ARIA SENZA FILI", "INVENZIONE"),
                ("NASCE INTERNET E IL MONDO DIVENTA CONNESSO IN POCHI SECONDI", "INFORMATICA"),
                ("PRIMO AEREO CHE DECOLLA E DIMOSTRA CHE L UOMO PUO VOLARE DAVVERO", "AVIAZIONE"),
                ("SCOPERTA DEI VACCINI CHE RIDUCE MALATTIE MORTALI IN TUTTO IL MONDO", "MEDICINA"),
                ("MICROCHIP CHE RENDE POSSIBILI COMPUTER SEMPRE PIU PICCOLI E POTENTI", "ELETTRONICA"),
                ("TELESCOPO CHE PERMETTE DI OSSERVARE STELLE E PIANETI COME MAI PRIMA", "ASTRONOMIA")
            ],
            "ESPLORAZIONI E VIAGGI STORICI": [
                ("PRIMO GIRO DEL MONDO COMPLETATO DOPO ANNI DI MARE E PERICOLI", "NAVIGAZIONE"),
                ("TRAVERSATA DELL ATLANTICO IN SOLITARIA CON UNA PICCOLA IMBARCAZIONE", "IMPRESA"),
                ("SPEDIZIONE TRA I GHIACCI DOVE IL FREDDO ROMPE IL RESPIRO E LA BUSSOLA", "POLI"),
                ("CAROVANA NEL DESERTO CHE SEGUE LE STELLE PER NON PERDERSI NEL NULLA", "DESERTO"),
                ("ATTRAVERSAMENTO DELLE ANDe CON POCA ACQUA E TANTA DETERMINAZIONE", "MONTAGNE"),
                ("VIAGGIO LUNGHISSIMO SU UNA VIA COMMERCIALE TRA SPEZIE SETA E PERICOLI", "ROTTE"),
                ("RAGGIUNGERE LA VETTA PIU ALTA CON OSSIGENO SCARSO E VENTO FEROCE", "ALPINISMO"),
                ("ATTRAVERSATA DELL OCEANO CON NAVI A VELA E MAPPE IMPERFETTE", "ESPLORATORI"),
                ("SPEDIZIONE NELLA GIUNGLA TRA INSETTI FIUMI E PIOGGE CONTINUE", "GIUNGLA"),
                ("PRIMO TRENO LUNGO CHE COLLEGA CITTA LONTANE E CAMBIA IL MODO DI VIAGGIARE", "FERROVIA")
            ],
            "CURIOSITA SUGLI ANIMALI": [
                ("IL POLPO HA TRE CUORI E IL SUO SANGUE E DI COLORE BLU", "MARE"),
                ("LE API COMUNICANO CON UNA DANZA PER INDICARE DOVE TROVARE IL NETTARE", "INSETTI"),
                ("I DELFINI USANO SUONI DIVERSI COME SE AVESSERO UN NOME PERSONALE", "MAMMIFERI MARINI"),
                ("IL CAMALEONTE CAMBIA COLORE ANCHE PER EMOZIONI E TEMPERATURA", "RETTILI"),
                ("LA GIRAFFA HA LO STESSO NUMERO DI VERTEBRE DEL COLLO DI UN ESSERE UMANO", "CURIOSITA"),
                ("I PINGUINI SI RICONOSCONO TRA MIGLIAIA GRAZIE ALLA VOCE", "ANIMALI POLARI"),
                ("I KOALA HANNO IMPRONTE DIGITALI MOLTO SIMILI A QUELLE UMANE", "AUSTRALIA"),
                ("IL NARVALO HA UNA LUNGA ZANNA A SPIRALE CHE SEMBRA UN CORNO", "ARTICO"),
                ("I CORVI RIESCONO A RISOLVERE PROBLEMI COMPLESSI USANDO STRUMENTI", "INTELLIGENZA"),
                ("IL BRADIPO SCENDE DALL ALBERO RARAMENTE E SI MUOVE CON CALMA ASSOLUTA", "FORESTA")
            ],
            "RECORD E PRIMATI ANIMALI": [
                ("IL GHEPARDO E IL FELINO PIU VELOCE SULLA TERRA IN CORSA BREVE", "RECORD"),
                ("IL FALCO PELLEGRINO E IL PIU VELOCE IN PICCHIATA QUANDO CACCIA", "VOLATILI"),
                ("LA BALENOTTERA AZZURRA E IL PIU GRANDE ANIMALE MAI ESISTITO", "OCEANO"),
                ("LA FORMICA PUO TRASPORTARE PESI MOLTE VOLTE SUPERIORI AL SUO CORPO", "FORZA"),
                ("IL COLIBRI BATTE LE ALI COSI VELOCE CHE SEMBRA FERMO IN ARIA", "UCCELLI"),
                ("IL CAMMELLO PUO RESTARE A LUNGO SENZA BERE GRAZIE AL SUO METABOLISMO", "DESERTO"),
                ("IL POLARE ORSO HA UN OLFATTO POTENTISSIMO PER TROVARE PREDE DA LONTANO", "ARTICO"),
                ("LA RANA FRECCIA HA UNA PELLE TOSSICA CHE PUO ESSERE PERICOLOSA", "ANFIBI"),
                ("IL LUFARDO DI MARE PUO NUOTARE PER MIGLIAIA DI CHILOMETRI SENZA FERMARSI", "MIGRAZIONI"),
                ("IL CAVALLUCCIO MARINO MASCHIO E QUELLO CHE PORTA IN GREMBO I PICCOLI", "STRANEZZE")
            ],
            "SPAZIO E UNIVERSO": [
                ("LA LUCE DEL SOLE IMPIEGA CIRCA OTTO MINUTI PER ARRIVARE FINO A NOI", "ASTRONOMIA"),
                ("UN BUCO NERO HA UNA GRAVITA COSI FORTE CHE NEMMENO LA LUCE SCAPPA", "COSMO"),
                ("LA STAZIONE SPAZIALE ORBITA INTORNO ALLA TERRA PIU VOLTE AL GIORNO", "MISSIONI"),
                ("MARTE VIENE CHIAMATO PIANETA ROSSO PER IL COLORE DEL SUO SUOLO", "PIANETI"),
                ("GIOVE HA UNA TEMPESTA GIGANTESCA VISIBILE DA SECOLI CHIAMATA MACCHIA ROSSA", "GIGANTI"),
                ("SATURNO E FAMOSO PER I SUOI ANELLI FATTI DI GHIACCIO E ROCCIA", "SISTEMA SOLARE"),
                ("LE STELLE CADENTI SONO PICCOLI FRAMMENTI CHE BRUCIANO NELL ATMOSFERA", "FENOMENI"),
                ("LA VIA LATTEA E LA GALASSIA IN CUI SI TROVA IL NOSTRO SISTEMA SOLARE", "GALASSIE"),
                ("L ECLISSI SOLARE ACCADE QUANDO LA LUNA COPRE IL DISCO DEL SOLE", "ECLISSI"),
                ("UN ANNO LUCE E UNA DISTANZA ENORME PERCORSA DALLA LUCE IN UN ANNO", "MISURE")
            ],
            "NATURA E FENOMENI STRABILIANTI": [
                ("L ARCobaleno NASCE QUANDO LA LUCE SI DIVIDE PASSANDO TRA GOCCE D ACQUA", "METEO"),
                ("UN FULMINE PUO SCALDARE L ARIA COSA TANTO DA CREARE UN TUONO ASSORDANTE", "TEMPESTE"),
                ("LE AURORE POLARI COLORANO IL CIELO PER L INCONTRO TRA SOLE E CAMPO MAGNETICO", "POLI"),
                ("I GEYSER SPRUZZANO ACQUA BOLLENTE DAL SOTTOSUOLO IN ERUZIONI REGOLARI", "GEOLOGIA"),
                ("LE MAREE CAMBIANO IL LIVELLO DEL MARE PER EFFETTO DELLA LUNA", "OCEANO"),
                ("UNA VALANGA SCENDE VELOCE QUANDO LA NEVE PERDE STABILITA SUL PENDIO", "MONTAGNA"),
                ("I VULCANI POSSONO ERUTTARE CENERE LAVA E GAS IN POCHI MINUTI", "VULCANI"),
                ("UNA NEVICATA SILENZIOSA CAMBIA IL PAESAGGIO E ATTUTISCE OGNI SUONO", "INVERNO"),
                ("LE DUNE DEL DESERTO CAMBIANO FORMA SPINTE DAL VENTO PER GIORNI", "DESERTO"),
                ("UNA CASCATA RUMOROSA NASCONDE SPESSO UNA GROTTA DIETRO IL GETTO", "NATURA")
            ]
        }

        # Pulisce DB precedente per evitare duplicati
        Frase.objects.all().delete()
        Categoria.objects.all().delete()
        self.stdout.write("Database pulito. Inizio inserimento nuove frasi...")

        totale_inseriti = 0

        for cat_nome, lista_frasi in dataset.items():
            categoria, _ = Categoria.objects.get_or_create(nome=cat_nome)

            for testo, suggerimento in lista_frasi:
                Frase.objects.create(
                    testo=testo,
                    suggerimento=suggerimento,
                    categoria=categoria
                )
                totale_inseriti += 1

        self.stdout.write(self.style.SUCCESS(f'Fatto! Inserite {totale_inseriti} frasi.'))