from django.core.management.base import BaseCommand
from game.models import Categoria, Frase, ConfigurazioneGioco
from django.contrib.auth.models import User
import os

class Command(BaseCommand):
    help = 'Popola il database con categorie cinema/storia/animali e crea Superuser se manca'

    def handle(self, *args, **kwargs):
        # ---------------------------------------------------------
        # 1. GESTIONE SUPERUSER (Creazione o Aggiornamento)
        # ---------------------------------------------------------
        nome_admin = os.environ.get('DJANGO_SUPERUSER_USERNAME', 'admin')
        pass_admin = os.environ.get('DJANGO_SUPERUSER_PASSWORD', 'admin123')
        email_admin = os.environ.get('DJANGO_SUPERUSER_EMAIL', 'admin@example.com')
        
        try:
            # Cerca l'utente. Se non c'è, lo crea.
            user, created = User.objects.get_or_create(
                username=nome_admin,
                defaults={'email': email_admin}
            )
            
            # IMPOSIZIONE DELLA PASSWORD (LO FA SEMPRE)
            user.set_password(pass_admin)
            user.is_superuser = True
            user.is_staff = True
            user.save()
            
            if created:
                self.stdout.write(self.style.SUCCESS(f'✅ UTENTE CREATO: {nome_admin}'))
            else:
                self.stdout.write(self.style.SUCCESS(f'✅ PASSWORD AGGIORNATA per utente esistente: {nome_admin}'))
                
        except Exception as e:
             self.stdout.write(self.style.ERROR(f'❌ Errore utente: {e}'))

        # ---------------------------------------------------------
        # 2. CONFIGURAZIONE ROUND
        # ---------------------------------------------------------
        if not ConfigurazioneGioco.objects.exists():
            ConfigurazioneGioco.objects.create(numero_round_per_partita=3)
            self.stdout.write(self.style.SUCCESS('✅ Configurazione Round creata (3 round).'))

        # ---------------------------------------------------------
        # 3. POPOLAMENTO FRASI (Il tuo nuovo Dataset)
        # ---------------------------------------------------------
        dataset = {
            "CINEMA FRASI ICONICHE PARAFRASATE": [
                ("CHE LA FORZA POSSA ACCOMPAGNARTI SEMPRE IN OGNI BATTAGLIA DELLA GALASSIA", "FILM DI FANTASCIENZA"),
                ("LA VITA SOMIGLIA A UNA SCATOLA DI CIOCCOLATINI E NON SAI MAI COSA TROVI", "FILM DRAMMATICO"),
                ("TI FARO UNA PROPOSTA CHE NON POTRAI RIFIUTARE DETTA CON CALMA E MINACCIA", "FILM DI MAFIA"),
                ("NON E IL CUCCHIAIO CHE SI PIEGA MA IL TUO MODO DI GUARDARE LA REALTA", "FILM CULT"),
                ("NON CONTA QUANTO COLPISCI MA QUANTO RESISTI E CONTINUI AD ANDARE AVANTI", "FILM SPORTIVO"),
                ("NESSUN POSTO AL MONDO E COME CASA QUANDO FINISCE UN VIAGGIO STRANO", "FILM FANTASTICO"),
                ("QUESTO POTREBBE ESSERE L INIZIO DI UNA GRANDE AMICIZIA NATA PER CASO", "FILM ROMANTICO"),
                ("PROMETTO CHE TORNERO PRESTO CON LO SGUARDO DI ACCIAIO E PASSI PESANTI", "FILM D AZIONE"),
                ("VOGLIO TELEFONARE PER DIRE CHE DESIDERO SOLO TORNARE A CASA", "FILM FANTASCIENZA"),
                ("LA VITA TROVA SEMPRE UNA STRADA ANCHE QUANDO PENSI DI AVER CONTROLLATO TUTTO", "FILM CON DINOSAURI")
            ],
            "CINEMA SCENE FAMOSE": [
                ("UN ARCHEOLOGO CON CAPPELLO E FRUSTA CORRE DAVANTI A UNA ROCCIA GIGANTE", "AVVENTURA"),
                ("DUE AMANTI A PRUA CON LE BRACCIA APERTE COME SE STESSERO VOLANDO", "FILM ROMANTICO"),
                ("UN DETECTIVE CAMMINA SOTTO LA PIOGGIA TRA LUCI AL NEON E OMBRE", "THRILLER"),
                ("UN MAGO RAGAZZO CON OCCHIALI SCOPRE UNA SCUOLA SEGRETA PIENA DI INCANTESIMI", "MAGIA"),
                ("UN EROE IN MASCHERA OSCURA OSSERVA LA CITTA DALL ALTO DI UN GRATTACIELO", "SUPEREROI"),
                ("UN RE LEONE GUARDA IL CIELO E RICORDA LE PAROLE DEL PADRE", "ANIMAZIONE"),
                ("UN ROBOT SOLITARIO RACCOGLIE OGGETTI SU UNA TERRA DESERTA PIENA DI SILENZIO", "FUTURO"),
                ("UNA CORSA IN AUTO TRA TRAFFICO E POLIZIA CON MUSICA A TUTTO VOLUME", "INSEGUIMENTO"),
                ("UN UOMO IN COMPLETO NERO SCHIVA COLPI AL RALLENTATORE COME FOSSE IMPOSSIBILE", "AZIONE"),
                ("UNA BATTAGLIA SOTTO LA PIOGGIA CON SPADATE E URA CHE NON FINISCONO", "FILM EPICO")
            ],
            "EVENTI STORICI MONDIALI": [
                ("SBARCO IN NORMANDIA IL SEI GIUGNO MILLENOVECENTOQUARANTAQUATTRO", "SECONDA GUERRA MONDIALE"),
                ("CADUTA DEL MURO DI BERLINO CHE DIVIDEVA UNA CITTA IN DUE MONDI", "GUERRA FREDDA"),
                ("PRIMO PASSO UMANO SULLA LUNA CON UNA FRASE CHE FECE IL GIRO DEL MONDO", "SPAZIO"),
                ("FIRMA DEL TRATTATO CHE POSE FINE A UNA GUERRA DEVASTANTE IN EUROPA", "PACE"),
                ("SCOPERTA DELL AMERICA CON TRE NAVI E UN VIAGGIO SENZA CERTEZZE", "ESPLORAZIONI"),
                ("RIVOLUZIONE FRANCESE CON PRESA DELLA BASTIGLIA E CAMBIAMENTO RADICALE", "RIVOLUZIONE"),
                ("AFFONDA IL TITANIC NELLA NOTTE GELIDA DOPO L IMPATTO CON UN ICEBERG", "TRAGEDIA"),
                ("PRIMO UOMO NELLO SPAZIO ORBITA INTORNO ALLA TERRA E TORNA VIVO", "COSMONAUTA"),
                ("FINE DELLA SECONDA GUERRA MONDIALE CON FESTEGGIAMENTI IN STRADA", "STORIA"),
                ("SCOPERTA DELLA PENICILLINA CHE CAMBIO PER SEMPRE LA MEDICINA MODERNA", "SCIENZA")
            ],
            "EVENTI STORICI ITALIANI": [
                ("ERUZIONE DEL VESUVIO CHE SEPPELLI POMPEI SOTTO CENERE E LAPILLI", "ANTICA ROMA"),
                ("UNIFICAZIONE D ITALIA CON NASCITA DEL REGNO E SPERANZE DI UN POPOLO", "RISORGIMENTO"),
                ("ROMA DIVENTA CAPITALE E CAMBIA IL VOLTO POLITICO DELLA NAZIONE", "STORIA D ITALIA"),
                ("ALLUVIONE DI FIRENZE CON FANGO OVUNQUE E VOLONTARI DA TUTTO IL MONDO", "NOVECENTO"),
                ("COSTRUZIONE DEL COLOSSEO COME SIMBOLO DI POTENZA E SPETTACOLO", "IMPERI ROMANI"),
                ("PROCESSI E INCHIESTE CHE SCOSSONO LA POLITICA ITALIANA NEGLI ANNI NOVANTA", "CRONACA"),
                ("IL PRIMO TRAFORO CHE ATTRAVERSA LA MONTAGNA E COLLEGA DUE STATI", "INGEGNERIA"),
                ("FESTA DELLA REPUBBLICA CON IL REFERENDUM CHE CAMBIA LA FORMA DI STATO", "REFERENDUM"),
                ("TERREMOTO DEVASTANTE CON PAESI DISTRUTTI E RICOSTRUZIONE LUNGHISSIMA", "CALAMITA"),
                ("LA NASCITA DI UN GRANDE MARCHIO AUTOMOBILISTICO CHE DIVENTA SIMBOLO ITALIANO", "MOTORI")
            ],
            "SCOPERTE E INVENZIONI": [
                ("INVENZIONE DELLA STAMPA A CARATTERI MOBILI CHE DIFFONDE LIBRI OVUNQUE", "COMUNICAZIONE"),
                ("SCOPERTA DEL DNA COME CODICE DELLA VITA CON STRUTTURA A DOPPIA ELICA", "BIOLOGIA"),
                ("PRIMA LAMPADINA ELETTRICA CHE PORTA LUCE NELLE CASE E NELLE STRADE", "ELETTRICITA"),
                ("PRIMO TELEFONO CHE PERMETTE DI PARLARE A DISTANZA SENZA MUOVERSI", "TECNOLOGIA"),
                ("PRIMA RADIO CHE TRASMETTE VOCI E MUSICA NELL ARIA SENZA FILI", "INVENZIONE"),
                ("NASCE INTERNET E IL MONDO DIVENTA CONNESSO IN POCHI SECONDI", "INFORMATICA"),
                ("PRIMO AEREO CHE DECOLLA E DIMOSTRA CHE L UOMO PUO VOLARE DAVVERO", "AVIAZIONE"),
                ("SCOPERTA DEI VACCINI CHE RIDUCE MALATTIE MORTALI IN TUTTO IL MONDO", "MEDICINA"),
                ("MICROCHIP CHE RENDE POSSIBILI COMPUTER SEMPRE PIU PICCOLI E POTENTI", "ELETTRONICA"),
                ("TELESCOPO CHE PERMETTE DI OSSERVARE STELLE E PIANETI COME MAI PRIMA", "ASTRONOMIA")
            ],
            "ESPLORAZIONI E VIAGGI STORICI": [
                ("PRIMO GIRO DEL MONDO COMPLETATO DOPO ANNI DI MARE E PERICOLI", "NAVIGAZIONE"),
                ("TRAVERSATA DELL ATLANTICO IN SOLITARIA CON UNA PICCOLA IMBARCAZIONE", "IMPRESA"),
                ("SPEDIZIONE TRA I GHIACCI DOVE IL FREDDO ROMPE IL RESPIRO E LA BUSSOLA", "POLI"),
                ("CAROVANA NEL DESERTO CHE SEGUE LE STELLE PER NON PERDERSI NEL NULLA", "DESERTO"),
                ("ATTRAVERSAMENTO DELLE ANDe CON POCA ACQUA E TANTA DETERMINAZIONE", "MONTAGNE"),
                ("VIAGGIO LUNGHISSIMO SU UNA VIA COMMERCIALE TRA SPEZIE SETA E PERICOLI", "ROTTE"),
                ("RAGGIUNGERE LA VETTA PIU ALTA CON OSSIGENO SCARSO E VENTO FEROCE", "ALPINISMO"),
                ("ATTRAVERSATA DELL OCEANO CON NAVI A VELA E MAPPE IMPERFETTE", "ESPLORATORI"),
                ("SPEDIZIONE NELLA GIUNGLA TRA INSETTI FIUMI E PIOGGE CONTINUE", "GIUNGLA"),
                ("PRIMO TRENO LUNGO CHE COLLEGA CITTA LONTANE E CAMBIA IL MODO DI VIAGGIARE", "FERROVIA")
            ],
            "CURIOSITA SUGLI ANIMALI": [
                ("IL POLPO HA TRE CUORI E IL SUO SANGUE E DI COLORE BLU", "MARE"),
                ("LE API COMUNICANO CON UNA DANZA PER INDICARE DOVE TROVARE IL NETTARE", "INSETTI"),
                ("I DELFINI USANO SUONI DIVERSI COME SE AVESSERO UN NOME PERSONALE", "MAMMIFERI MARINI"),
                ("IL CAMALEONTE CAMBIA COLORE ANCHE PER EMOZIONI E TEMPERATURA", "RETTILI"),
                ("LA GIRAFFA HA LO STESSO NUMERO DI VERTEBRE DEL COLLO DI UN ESSERE UMANO", "CURIOSITA"),
                ("I PINGUINI SI RICONOSCONO TRA MIGLIAIA GRAZIE ALLA VOCE", "ANIMALI POLARI"),
                ("I KOALA HANNO IMPRONTE DIGITALI MOLTO SIMILI A QUELLE UMANE", "AUSTRALIA"),
                ("IL NARVALO HA UNA LUNGA ZANNA A SPIRALE CHE SEMBRA UN CORNO", "ARTICO"),
                ("I CORVI RIESCONO A RISOLVERE PROBLEMI COMPLESSI USANDO STRUMENTI", "INTELLIGENZA"),
                ("IL BRADIPO SCENDE DALL ALBERO RARAMENTE E SI MUOVE CON CALMA ASSOLUTA", "FORESTA")
            ],
            "RECORD E PRIMATI ANIMALI": [
                ("IL GHEPARDO E IL FELINO PIU VELOCE SULLA TERRA IN CORSA BREVE", "RECORD"),
                ("IL FALCO PELLEGRINO E IL PIU VELOCE IN PICCHIATA QUANDO CACCIA", "VOLATILI"),
                ("LA BALENOTTERA AZZURRA E IL PIU GRANDE ANIMALE MAI ESISTITO", "OCEANO"),
                ("LA FORMICA PUO TRASPORTARE PESI MOLTE VOLTE SUPERIORI AL SUO CORPO", "FORZA"),
                ("IL COLIBRI BATTE LE ALI COSI VELOCE CHE SEMBRA FERMO IN ARIA", "UCCELLI"),
                ("IL CAMMELLO PUO RESTARE A LUNGO SENZA BERE GRAZIE AL SUO METABOLISMO", "DESERTO"),
                ("IL POLARE ORSO HA UN OLFATTO POTENTISSIMO PER TROVARE PREDE DA LONTANO", "ARTICO"),
                ("LA RANA FRECCIA HA UNA PELLE TOSSICA CHE PUO ESSERE PERICOLOSA", "ANFIBI"),
                ("IL LUFARDO DI MARE PUO NUOTARE PER MIGLIAIA DI CHILOMETRI SENZA FERMARSI", "MIGRAZIONI"),
                ("IL CAVALLUCCIO MARINO MASCHIO E QUELLO CHE PORTA IN GREMBO I PICCOLI", "STRANEZZE")
            ],
            "SPAZIO E UNIVERSO": [
                ("LA LUCE DEL SOLE IMPIEGA CIRCA OTTO MINUTI PER ARRIVARE FINO A NOI", "ASTRONOMIA"),
                ("UN BUCO NERO HA UNA GRAVITA COSI FORTE CHE NEMMENO LA LUCE SCAPPA", "COSMO"),
                ("LA STAZIONE SPAZIALE ORBITA INTORNO ALLA TERRA PIU VOLTE AL GIORNO", "MISSIONI"),
                ("MARTE VIENE CHIAMATO PIANETA ROSSO PER IL COLORE DEL SUO SUOLO", "PIANETI"),
                ("GIOVE HA UNA TEMPESTA GIGANTESCA VISIBILE DA SECOLI CHIAMATA MACCHIA ROSSA", "GIGANTI"),
                ("SATURNO E FAMOSO PER I SUOI ANELLI FATTI DI GHIACCIO E ROCCIA", "SISTEMA SOLARE"),
                ("LE STELLE CADENTI SONO PICCOLI FRAMMENTI CHE BRUCIANO NELL ATMOSFERA", "FENOMENI"),
                ("LA VIA LATTEA E LA GALASSIA IN CUI SI TROVA IL NOSTRO SISTEMA SOLARE", "GALASSIE"),
                ("L ECLISSI SOLARE ACCADE QUANDO LA LUNA COPRE IL DISCO DEL SOLE", "ECLISSI"),
                ("UN ANNO LUCE E UNA DISTANZA ENORME PERCORSA DALLA LUCE IN UN ANNO", "MISURE")
            ],
            "NATURA E FENOMENI STRABILIANTI": [
                ("L ARCobaleno NASCE QUANDO LA LUCE SI DIVIDE PASSANDO TRA GOCCE D ACQUA", "METEO"),
                ("UN FULMINE PUO SCALDARE L ARIA COSA TANTO DA CREARE UN TUONO ASSORDANTE", "TEMPESTE"),
                ("LE AURORE POLARI COLORANO IL CIELO PER L INCONTRO TRA SOLE E CAMPO MAGNETICO", "POLI"),
                ("I GEYSER SPRUZZANO ACQUA BOLLENTE DAL SOTTOSUOLO IN ERUZIONI REGOLARI", "GEOLOGIA"),
                ("LE MAREE CAMBIANO IL LIVELLO DEL MARE PER EFFETTO DELLA LUNA", "OCEANO"),
                ("UNA VALANGA SCENDE VELOCE QUANDO LA NEVE PERDE STABILITA SUL PENDIO", "MONTAGNA"),
                ("I VULCANI POSSONO ERUTTARE CENERE LAVA E GAS IN POCHI MINUTI", "VULCANI"),
                ("UNA NEVICATA SILENZIOSA CAMBIA IL PAESAGGIO E ATTUTISCE OGNI SUONO", "INVERNO"),
                ("LE DUNE DEL DESERTO CAMBIANO FORMA SPINTE DAL VENTO PER GIORNI", "DESERTO"),
                ("UNA CASCATA RUMOROSA NASCONDE SPESSO UNA GROTTA DIETRO IL GETTO", "NATURA")
            ],

            "FILM ITALIANI SCENE CULT": [
                ("TRE AMICI IN VIAGGIO CON UNA GAMBA DI LEGNO E UNA SERIE DI DISASTRI IMPROVVISI", "COMMEDIA ITALIANA"),
                ("UN RAGAZZO DI CAMPAGNA ARRIVA IN CITTA E FINISCE IN GUAI ASSURDI E INESPLICABILI", "COMMEDIA ITALIANA"),
                ("DUE AMICI SI RITROVANO A PARLARE DELLA VITA TRA RISATE E MALINCONIA IMPROVVISA", "AMICIZIA"),
                ("UN PERSONAGGIO SI GIUSTIFICA CON SINCERITA DISARMANTE DOPO UNA FIGURA BARBINA EPICA", "SCENA ICONICA"),
                ("UN UOMO CERCA DI FARE IL FURBO MA FINISCE SEMPRE PER PEGGIORARE LA SITUAZIONE", "SITUAZIONE COMICA"),
                ("UNA CENA TRA PARENTI DIVENTA UN CAMPO DI BATTAGLIA TRA FRECCIATE E SILENZI PESANTI", "FAMIGLIA"),
                ("UN GRUPPO DI AMICI ORGANIZZA UN PIANO PERFETTO CHE CROLLA AL PRIMO IMPREVISTO", "PIANO FALLITO"),
                ("UN PERSONAGGIO SI LAMENTA DELLA VITA QUOTIDIANA CON IRONIA E RASSEGNAZIONE", "SFOGO"),
                ("UN UOMO E UNA DONNA SI INCONTRANO PER CASO E NASCE UNA STORIA PIENA DI OSTACOLI", "ROMANTICO"),
                ("UN DISCORSO IMPROVVISATO DAVANTI A TUTTI CAMBIA L UMORE DELLA SERATA", "COLPO DI SCENA")
            ],

            "CINEMA CRIME E MAFIA": [
                ("UN CAPO CARISMATICO PARLA PIANO MA TUTTI OBBEDISCONO SENZA FIATARE", "BOSS"),
                ("UNA STRETTA DI MANO DURANTE UNA FESTA NASCONDE UN ACCORDO SEGRETO", "PATTO"),
                ("UNA VALIGETTA PIENA DI SOLDI PASSA DI NOTTE IN UN PARCHEGGIO VUOTO", "SCAMBIO"),
                ("UN INVESTIGATORE SEGUE UNA PISTA E SI RITROVA DAVANTI A UNA VERITA SCOMODA", "INDAGINE"),
                ("UNA TELEFONATA BREVE CAMBIA IL DESTINO DI UNA FAMIGLIA POTENTE", "MINACCIA"),
                ("UN TESTIMONE ESITA PRIMA DI PARLARE PERCHE HA PAURA DI RITORSIONI", "PAURA"),
                ("UNA RIUNIONE IN UNA STANZA FUMOSA DECIDE IL FUTURO DI UNA CITTA", "DECISIONE"),
                ("UN TRADIMENTO INASPETTATO ARRIVA DA CHI SEMBRAVA PIU FIDATO", "TRADIMENTO"),
                ("UN INSEGUIMENTO NOTTURNO FINISCE IN UN VICOLo STRETTO SENZA USCITA", "FUGA"),
                ("UN UOMO DICE CHE E SOLO AFFARI MA TUTTI CAPISCONO CHE E PERSONALE", "REGOLA")
            ],

            "CINEMA FANTASCIENZA CULT": [
                ("UN EQUIPAGGIO NELLO SPAZIO RICEVE UN SEGNALE E SI DIRIGE VERSO L IGNOTO", "MISSIONE"),
                ("UN ROBOT IMPARA EMOZIONI E COMINCIA A FARE DOMANDE SULLA VITA", "INTELLIGENZA ARTIFICIALE"),
                ("UN VIAGGIO NEL TEMPO CREA PARADOSSI E CAMBIA IL PRESENTE IN MODO STRANO", "TEMPO"),
                ("UNA SIMULAZIONE PERFETTA FA DUBITARE DI CIO CHE E REALE OGNI GIORNO", "REALTA"),
                ("UNA CITTA FUTURISTICA PIENA DI NEON NASCONDE SEGRETI TRA OMBRE E PIOGGIA", "FUTURO"),
                ("UN ALIENO SI NASCONDE TRA GLI UMANI E LASCIA INDIZI DI UNA VERITA INQUIETANTE", "EXTRATERRESTRE"),
                ("UN DISPOSITIVO MISTERIOSO SI ATTIVA E APRE UNA PORTA VERSO UN ALTRO MONDO", "PORTALE"),
                ("UNA NAVE ENORME APPARE NEL CIELO E TUTTI ASPETTANO UN SEGNO", "INVASIONE"),
                ("UN UOMO SI SVEGLIA E SCOPRE CHE IL SUO RICORDO E STATO MANIPOLATO", "MEMORIA"),
                ("UNA BATTAGLIA TRA NAVI SPAZIALI SI DECIDE CON UNA MANOVRA IMPOSSIBILE", "GALASSIA")
            ],

            "STORIA ROMA ANTICA": [
                ("GIULIO CESARE ATTRAVERSA IL RUBICONE E SEGNA UN PUNTO DI NON RITORNO", "DECISIONE STORICA"),
                ("L INCENDIO DI ROMA SCUOTE LA CAPITALE E ALIMENTA SOSPETTI E PAURE", "CRISI"),
                ("GLADIATORI COMBATTONO NELL ARENA DAVANTI A UNA FOLLA CHE RUGGISCE", "COLOSSEO"),
                ("SPARTACO GUIDA UNA RIVOLTA DI SCHIAVI CONTRO UN IMPERO POTENTISSIMO", "RIVOLTA"),
                ("AUGUSTO CONSOLIDA IL POTERE E TRASFORMA LA REPUBBLICA IN IMPERO", "IMPERATORE"),
                ("LE LEGIONI ROMANE MARCIANO IN FORMAZIONE CON SCUDI E DISCIPLINA PERFETTA", "LEGIONI"),
                ("UN SENATORE PRONUNCIA UN DISCORSO ACCESO E LA POLITICA DIVENTA GUERRA", "SENATO"),
                ("LA COSTRUZIONE DI STRADE E ACQUEDOTTI CAMBIA LA VITA DI MILIONI DI PERSONE", "INGEGNERIA"),
                ("UNA CONGIURA NASCOSTA TRA TUNICHE E PUGNALI SCUOTE IL CUORE DI ROMA", "CONGIURA"),
                ("UNA VITTORIA MILITARE VIENE FESTEGGIATA CON UN TRIONFO LUNGO LE VIE", "TRIONFO")
            ],

            "STORIA MEDIEVO E CASTELLI": [
                ("UN CAVALIERE PARTE ALL ALBA PER UNA MISSIONE CHE SEMBRA IMPOSSIBILE", "CAVALIERI"),
                ("UN ASSALTO AL CASTELLO CON SCALE E ARIETI IN MEZZO A FIAMME E URla", "ASSEDIO"),
                ("UN RE FIRMA UN EDITTO CHE CAMBIA LE REGOLE PER TUTTO IL REGNO", "REGNO"),
                ("UN TORNEO CON LANCE E ARMATURE ATTIRA FOLLE E PROMESSE DI GLORIA", "TORNEO"),
                ("UN MONACO COPIA MANOSCRITTI A LUME DI CANDELA IN SILENZIO ASSOLUTO", "MONASTERO"),
                ("UNA CARESTIA METTE IN GINOCCHIO I VILLAGGI E NASCONO RIBELLIONI", "CRISI"),
                ("UN MESSAGGERO ARRIVA A CAVALLO CON NOTIZIE URGENTI DAL CONFINE", "MESSAGGIO"),
                ("UNA REGINA ORGANIZZA UN MATRIMONIO POLITICO PER EVITARE UNA GUERRA", "ALLEANZA"),
                ("UNA BATTAGLIA IN CAMPO APERTO DECIDE IL DESTINO DI UNA DINASTIA", "BATTAGLIA"),
                ("UN DRAPPO VIENE ISSATO SULLE MURA COME SEGNO DI VITTORIA", "VITTORIA")
            ],

            "GRANDI IMPRESE SPORTIVE": [
                ("UNA FINALE DECISA AI RIGORI CON SILENZIO PRIMA DEL TIRO E URLO DOPO IL GOL", "CALCIO"),
                ("UN MARATONETA TAGLIA IL TRAGUARDO STREMATO DOPO CHILOMETRI DI FATICA", "ATLETICA"),
                ("UNA RIMONTA INCREDIBILE NEGLI ULTIMI MINUTI CAMBIA IL RISULTATO", "RIMONTA"),
                ("UN CAMPIONE ALZA LA COPPA SOTTO UNA PIOGGIA DI CORIANDOLI", "VITTORIA"),
                ("UNA VOLATA IN BICICLETTA SULL ARRIVO CON RUOTE AFFIANCATE FINO ALL ULTIMO", "CICLISMO"),
                ("UNA PARTITA DI TENNIS FINISCE DOPO ORE CON UN PUNTO CHE SEMBRA IMPOSSIBILE", "TENNIS"),
                ("UN RECORD DEL MONDO CADE DAVANTI A TUTTI E IL PUBBLICO RESTA SENZA FIATO", "RECORD"),
                ("UNA SCHIACCIATA A DUE MANI CHIUDE LA GARA E FA ESPLODERE IL PALAZZETTO", "BASKET"),
                ("UNA PARATA DECISIVA ALL ULTIMO SECONDO SALVA LA SQUADRA DALLA SCONFITTA", "PORTIERE"),
                ("UN ALLENATORE URLA ISTRUZIONI E CAMBIA LA TATTICA NEL MOMENTO CRUCIALE", "STRATEGIA")
            ],

            "ARTE E CAPOLAVORI FAMOSI": [
                ("UN SORRISO ENIGMATICO IN UN RITRATTO CHE TUTTI RICONOSCONO SUBITO", "PITTURA"),
                ("UN AFFRESCO CON MANI CHE QUASI SI TOCCANO SU UNA VOLTA IMMensa", "CAPPELLA"),
                ("UNA STATUA DI MARMO PERFETTA CHE MOSTRA MUSCOLI E SGUARDO DECISO", "SCULTURA"),
                ("UN QUADRO CON ORECCHIO BENDATO E SGUARDO INTENSO PIENO DI SILENZIO", "PITTURA"),
                ("UN UOMO CHE PENSA SEDUTO CON IL MENTO SULLA MANO IN POSA CELEBRE", "SCULTURA"),
                ("UN URLO DIPINTO IN UN CIELO ONDULATO CHE TRASMETTE ANGOSCIA", "ESPRESSIONE"),
                ("UNA NOTTE PIENA DI STELLE E TURBINI DI LUCE DIPINTA CON PENNELLATE FORTI", "NOTTE STELLATA"),
                ("UN PALAZZO IMponente CON CUPOLA GIGANTE CHE DOMINA UNA CITTA", "ARCHITETTURA"),
                ("UNA MASCHERA TEATRALE CHE DIVENTA SIMBOLO DI UNA CULTURA ANTICA", "TEATRO"),
                ("UN PONTE FAMOSO FOTOGRAFATO DA MILIONI DI TURISTI OGNI ANNO", "MONUMENTO")
            ],

            "MITOLOGIA GRECA E LEGGENDE": [
                ("UN EROE AFFRONTA UN MOSTRO NEL LABIRINTO SEGUENDO UN FILO PER TORNARE INDIETRO", "LABIRINTO"),
                ("UN VIAGGIO LUNGO PER MARE TRA SIRENE CICLOPI E INGANNI CONTINUI", "ODISSEA"),
                ("UN UOMO VOLa TROPPO VICINO AL SOLE E LE ALI SI SCIOLGONO IN CIELO", "MITO"),
                ("UNA GUERRA NASCE PER UNA MELA D ORO E UN GIUDIZIO CHE DIVIDE TRE DEE", "TROIA"),
                ("UN RE TRASFORMA TUTTO IN ORO FINCHE CAPISCE CHE E UNA MALEDIZIONE", "MALEDIZIONE"),
                ("UNA DONNA APRE UN VASO PROIBITO E LIBERA GUAI CHE NON SI POSSONO FERMARE", "PANDORA"),
                ("UN GIGANTE CON UN OCCHIO SOLO VIENE INGANNATO CON ASTUZIA E PAZIENZA", "CICLOPE"),
                ("UN CAVALLO DI LEGNO ENTRA IN CITTA E CAMBIA PER SEMPRE IL DESTINO DI UNA GUERRA", "INGANNO"),
                ("UN DIO DEL MARE SCUOTE LE ONDE CON IL TRIDENTE E SCATENA TEMPESTE", "POSEIDONE"),
                ("UNA DISCESA NELL OLTRETOMBA PER RIPRENDERE CIO CHE SI E PERDUTO", "INFERI")
            ],

            "ANIMALI DEL MARE CURIOSITA": [
                ("IL PESCE PALLA SI GONFIA ALL IMPROVVISO PER SEMBRARE MOLTO PIU GRANDE", "DIFESA"),
                ("IL CALAMARO GIGANTE VIVE NEL PROFONDO E RARAMENTE SI MOSTRA", "ABISSI"),
                ("IL PESCE LANTERNA PRODUCE LUCE PER ATTIRARE PREDE NEL BUIO TOTALE", "BIOLUMINESCENZA"),
                ("IL CAVALLUCCIO MARINO MASCHIO PORTA I PICCOLI FINO ALLA NASCITA", "STRANEZZE"),
                ("UNA MEDUSA PUO AVERE TENTACOLI LUNGHISSIMI CHE BRUCIANO COME FUOCO", "PERICOLO"),
                ("LE ORCHE CACCiano IN GRUPPO CON STRATEGIE CHE SEMBRANO STUDIATE", "COOPERAZIONE"),
                ("LA STELLA MARINA PUO RIGENERARE UN BRACCIO SE LO PERDE", "RIGENERAZIONE"),
                ("LO SQUALO DEVE NUOTARE SPESSO PER RESPIRARE E NON FERMARSI TROPPO", "SQUALI"),
                ("I CORALLI SONO ANIMALI E COSTRUISCONO BARRIERE CHE SEMBRANO CITTA SOTTOMARINE", "BARRIERA CORALLINA"),
                ("LA BALENA COMUNICA CON CANTI LUNGHI CHE VIAGGIANO PER CHILOMETRI", "CANTI")
            ],

            "MISSIONI SPAZIALI E SONDE": [
                ("UNA SONDA PASSA VICINO A UN PIANETA E INVIA FOTO CHE CAMBIANO I LIBRI DI SCIENZA", "SONDA"),
                ("UN ROVER SU MARTE ANALIZZA ROCCE E CERCA TRACCE DI ACQUA ANTICA", "MARTE"),
                ("UN SATELLITE RILEVA TEMPeste E NUVOLE PER PREVEDERE IL METEO", "SATELLITI"),
                ("UN RAZZO DECOLLA DI NOTTE E IL CIELO DIVENTA GIORNO PER QUALCHE SECONDO", "LANCIO"),
                ("UNA CAPSULA RIENTRA NELL ATMOSFERA E ATterra CON PARACADUTE", "RIENTRO"),
                ("UN TELESCOPIO SPAZIALE OSSERVA GALASSIE LONTANISSIME E NE RIVELA DETTAGLI", "TELESCOPIO"),
                ("UNA STAZIONE ORBITALE ACCOGLIE ASTRONAUTI CHE VIVONO IN ASSENZA DI GRAVITA", "ORBITA"),
                ("UNA MISSIONE RACCOGLIE CAMPIONI DI ROCCIA E LI RIPORTA SULLA TERRA", "CAMPIONI"),
                ("UN MODULO SI SGANCIA E SCENDE SU UNA SUPERFICIE SCONOSCIUTA CON MOTORI ACCESI", "ALLUNAGGIO"),
                ("UNA COMETA VIENE RAGGIUNTA E STUDIATA PER CAPIRE LE ORIGINI DEL SISTEMA SOLARE", "COMETA")
            ]
        }

        # Pulisce DB precedente per evitare duplicati
        Frase.objects.all().delete()
        Categoria.objects.all().delete()
        self.stdout.write("Database pulito. Inizio inserimento nuove frasi...")

        totale_inseriti = 0

        for cat_nome, lista_frasi in dataset.items():
            categoria, _ = Categoria.objects.get_or_create(nome=cat_nome)

            for testo, suggerimento in lista_frasi:
                Frase.objects.create(
                    testo=testo,
                    suggerimento=suggerimento,
                    categoria=categoria
                )
                totale_inseriti += 1

        self.stdout.write(self.style.SUCCESS(f'Fatto! Inserite {totale_inseriti} frasi.'))