# Generated by Django 4.2.25 on 2026-01-25 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partita',
            old_name='punteggio',
            new_name='turno_corrente',
        ),
        migrations.AddField(
            model_name='partita',
            name='vincitore',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Giocatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('punteggio', models.IntegerField(default=0)),
                ('partita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giocatori', to='game.partita')),
            ],
        ),
    ]
