# Generated by Django 4.2.25 on 2026-01-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_punteggio_partita_turno_corrente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partita',
            name='numero_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='partita',
            name='totale_rounds',
            field=models.IntegerField(default=3),
        ),
    ]
