# Generated by Django 4.2.25 on 2026-01-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_partita_numero_round_partita_totale_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='giocatore',
            name='montepremi_round',
            field=models.IntegerField(default=0),
        ),
    ]
