# Generated by Django 4.2.25 on 2026-01-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_giocatore_montepremi_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='frase',
            name='suggerimento',
            field=models.CharField(default='', help_text='Es: PINK FLOYD', max_length=100),
        ),
    ]
