# Generated by Django 4.2.25 on 2026-01-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_frase_suggerimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazioneGioco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_round_per_partita', models.IntegerField(default=3, help_text='Quante frasi bisogna indovinare per finire la partita?')),
                ('ricarica_frasi', models.BooleanField(default=False, help_text='⚠️ SPUNTA QUESTA CASELLA e clicca SALVA per cancellare e ricaricare tutte le frasi dal codice.')),
            ],
            options={
                'verbose_name': 'Impostazioni Gioco',
                'verbose_name_plural': 'Impostazioni Gioco',
            },
        ),
    ]
